# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "/Users/nazariiturchynovych/RiderProjects/EshopMicroservices/src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "/Users/nazariiturchynovych/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/nazariiturchynovych/RiderProjects/EshopMicroservices/src/Services/Basket/Basket.API:/app:rw"
    - "/Users/nazariiturchynovych/RiderProjects/EshopMicroservices/src:/src:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "/Users/nazariiturchynovych/RiderProjects/EshopMicroservices/src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "/Users/nazariiturchynovych/.microsoft/usersecrets:/home/app/.microsoft/usersecrets"
    - "/Users/nazariiturchynovych/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/nazariiturchynovych/RiderProjects/EshopMicroservices/src/Services/Catalog/Catalog.API:/app:rw"
    - "/Users/nazariiturchynovych/RiderProjects/EshopMicroservices/src:/src:rw"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "/Users/nazariiturchynovych/RiderProjects/EshopMicroservices/src"
      dockerfile: "Services/Discount/Discount.Grpc/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Discount.Grpc.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "discount.grpc:dev"
    ports: []
    volumes:
    - "/Users/nazariiturchynovych/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/nazariiturchynovych/RiderProjects/EshopMicroservices/src/Services/Discount/Discount.Grpc:/app:rw"
    - "/Users/nazariiturchynovych/RiderProjects/EshopMicroservices/src:/src:rw"
    working_dir: "/app"
